<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VoiceRemoteBridge.Core/VoiceRemoteBridge.Core.csproj" />
    <ProjectReference Include="../VoiceRemoteBridge.Windows/VoiceRemoteBridge.Windows.csproj" />
  </ItemGroup>
</Project>
